### ISSUE TITLE
UnboundLocalError: local variable 'whitelist' referenced before assignment

### ISSUE THREAD

**Issue by ponchofiesta** [alandmoore/wcgbrowser#11]
In current version seems to be an error. 'whitelist' is not initialised.

In line 317-318 you set whitelist = [] only if config paramemter whitelist is True. So I added this to fix the error:
```
            else:
            	whitelist = self.config.get("whitelist")
```

**Comment by alandmoore** [comment]
Thanks.  I've adjusted the code to fix the issue, though in a slightly different way.  Should be fixed by commit 1fd9863.
