### ISSUE TITLE
PyQt4 Windows

### ISSUE THREAD

**Issue by Daguerreo** [alandmoore/wcgbrowser#13]
On Windows, using the program as is with Qt5 works well, instead using Qt4 launch the exception:

usage: browser.py [-h] [-l START_URL] [-f] [-n] [-c CONFIG_FILE] [-d]
                  [--debug_log DEBUG_LOG] [-t TIMEOUT] [-i ICON_THEME]
                  [-z ZOOMFACTOR] [-p] [-u DEFAULT_USER] [-w DEFAULT_PASSWORD]
                  [-e] [-g] [--size WINDOW_SIZE] [--proxy_server PROXY_SERVER]
browser.py: error: unrecognized arguments: C:"mypath"/wcgbrowser/browser.py

using -c wcgbrowser.yaml don't change the situation. What's the matter?

Edit: it doesn't works with any optional flag or withuout flag

**Comment by alandmoore** [comment]
Can you let me know if this is still an issue?

**Comment by Daguerreo** [comment]
> Can you let me know if this is still an issue?

No idea sorry, I don't work in that project anymore.
