### ISSUE TITLE
is there something similar for raspberry?

### ISSUE THREAD

**Issue by matteoraggi** [alandmoore/wcgbrowser#14]
is there a similar browser for raspberry/raspbian?

**Comment by alandmoore** [comment]
There's no reason why wcgbrowser shouldn't work fine on raspbian, as far as I know.  It should work on any platform that has Python and Qt.

Have you tried it?  Does it work?

**Comment by hunternet93** [comment]
I've been using WCGBrowser on Raspbian for the last ~4 years, works just fine.

**Comment by alandmoore** [comment]
I have also confirmed that WCGbrowser works fine on Raspberry Pi and C.H.I.P. from NextThingCo.
