### ISSUE TITLE
Framebuffer

### ISSUE THREAD

**Issue by rogueturnip** [alandmoore/wcgbrowser#18]
I'm setting up a very simple kiosk on a pi and was wondering if wcg would work using the Linux framebuffer directly to output on an lcd. I can run x but if possible it would be nice to not have this overhead.

**Comment by alandmoore** [comment]
I haven't tried this.  It seems like others have asked about this before, but I don't recall if anyone has gotten it to work or not.  If you get it working, please let us know.
